.TH BAMBUSTUDIO 1 "May 2026" "bambustudio" "User Commands"
.SH NAME
bambustudio \- launch Bambu Studio
.SH SYNOPSIS
.B bambustudio
[\fIarguments\fR]
.SH DESCRIPTION
.B bambustudio
launches the repackaged official Bambu Studio AppImage installed by this
package.
.SH FILES
.TP
.I /opt/bambustudio/BambuStudio.AppImage
Bundled upstream AppImage.
.SH AUTHOR
Packaging maintained by daddyparodz.
